diplombank/bank/urls.py
from django.urls import path
from .views import *


app_name = "bank"

urlpatterns = [
    path('', BankView.as_view(), name='all'),
    path('deposit/', CreateBankView.as_view(), name='new'),
    path('single/', ClientList.as_view(), name='single'),
    path('view/<slag>/profit/', ProfitView.as_view(), name='margin'),
    path('view/', deposit_queryset, name='deposit'),
]

diplombank/diplombank/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from .views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bank.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('signup/', SignUpView.as_view(), name='signup')
]

diplombank/bank/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

User = get_user_model()


class Client(models.Model):
    deposit_sum = models.IntegerField(verbose_name='deposit amount')
    period = models.IntegerField(verbose_name='period in days',
                                 validators=[MinValueValidator(1), MaxValueValidator(360)],
                                 )
    client = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return f"/view/{self.client}/profit"


class CoursesDepositsBank(models.Model):
    date = models.DateField(verbose_name='date')
    usd = models.CharField(max_length=3, verbose_name='currency')
    usd_buy = models.FloatField(verbose_name='dollar purchase rate')
    usd_sale = models.FloatField(verbose_name='dollar selling rate')
    eur = models.CharField(max_length=3, verbose_name='currency')
    eur_buy = models.FloatField(verbose_name='euro purchase rate')
    eur_sale = models.FloatField(verbose_name='euro selling rate')
    rub = models.CharField(max_length=3, verbose_name='currency')
    rub_buy = models.FloatField(verbose_name='purchase rate RUB')
    rub_sale = models.FloatField(verbose_name='sale rate RUB')
    rate_byn = models.FloatField(verbose_name='deposit rate BYN')
    rate_usd = models.FloatField(verbose_name='deposit rate USD')
    rate_eur = models.FloatField(verbose_name='deposit rate EUR')
    rate_rub = models.FloatField(verbose_name='deposit rate RUB')


class ProfitDepositsClient(models.Model):
    date = models.DateField(verbose_name='date')
    profit_usd = models.FloatField(verbose_name='income at the deposit rate of USD')
    profit_eur = models.FloatField(verbose_name='income at the deposit rate of EUR')
    profit_rub = models.FloatField(verbose_name='income at the deposit rate of RUB')
    profit_byn = models.FloatField(verbose_name='income at the deposit rate of BYN')
    contributor = models.ForeignKey(Client, on_delete=models.CASCADE)

diplombank/bank/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from .method import *
from .models import *


class BankView(ListView):
    model = CoursesDepositsBank
    template_name = 'coursesdepositsbank_list.html'

    def get_queryset(self):
        date_now = date.today()
        read_or_load_courses_deposits_db()
        return super().get_queryset().filter(date=date_now)


class ClientList(ListView):
    model = Client
    fields = ['deposit_sum', 'period']


class ProfitView(ListView):
    model = ProfitDepositsClient
    template_name = 'profitdepositsclient_list.html'

    def get_queryset(self):
        query_client = Client.objects.filter(client=self.request.user).order_by('-id')
        data_profit = profit_deposits_client()
        for obj in data_profit:
            for i in query_client:
                if i.client == self.request.user:
                    query_profit = ProfitDepositsClient.objects.filter(contributor=i.id)
                    if query_profit.exists():
                        a = [j.contributor for j in query_profit]
                        for f in query_profit:
                            if f.contributor in a:
                                return super().get_queryset().filter(contributor=i.id)
                            else:
                                return None
                    else:
                        obj.save()
                        return super().get_queryset().filter(contributor=i.id)
                else:
                    return None


class CreateBankView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ['deposit_sum', 'period']
    success_url = reverse_lazy('bank:single')

    def form_valid(self, form):
        query_client = Client.objects.filter(client=self.request.user).order_by("-id")
        if query_client.exists():
            for i in query_client:
                if i.client == self.request.user:
                    query_delete = query_client.filter(client=self.request.user)
                    query_delete.delete()
                    obj = form.save(commit=False)
                    obj.client = self.request.user
                    obj.save()
                    return super().form_valid(form)
                else:
                    return None
        else:
            obj = form.save(commit=False)
            obj.client = self.request.user
            obj.save()
            return super().form_valid(form)


def deposit_queryset(request):
    query_client = Client.objects.filter(client=request.user).order_by('-id')
    if query_client.exists():
        for i in query_client:
            if i.client == request.user:
                return redirect(f'{i.client}/profit')
            else:
                return None
    else:
        return HttpResponse("Create your deposit")

diplombank/diplombank/views.py
from django.contrib.auth import get_user_model, authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import FormView

User = get_user_model()


class SignUpView(FormView):
    form_class = UserCreationForm
    template_name = "registration/login.html"
    extra_context = {"action": "Sign Up!"}
    success_url = reverse_lazy("bank:all")

    def form_valid(self, form):
        form.save()
        user = authenticate(
            username=form.cleaned_data.get("username"),
            password=form.clean_password2(),
        )
        login(self.request, user)
        return super().form_valid(form)

diplombank/bank/templates/bank/client_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DEPOSIT</title>
</head>
<body>
{% if user.is_authenticated %}
<p>Me:{{ user }}</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endif %}
</body>
</html>

diplombank/bank/templates/bank/client_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SINGLE</title>
</head>
<body>
    {% for i in object_list %}
    {% if i.client == user %}
    <p>Me:{{ user }}</p>
        <p><a href="{% url 'bank:all' %}">Home page()</a></p>
        <p><a href="{{ i.get_absolute_url }}">Calculate your deposit()</a></p>
    <hr>
    <hr>
    <table>
        <tr><td>Deposit amount</td>    <td>Period in days</td>
        <tr><td>{{ i.deposit_sum }}</td>    <td>{{ i.period }}</td>
    </table>
    {% endif %}
    {% endfor %}
</body>
</html>

diplombank/bank/templates/bank/coursesbank_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BANK</title>
</head>
<body>
<article>
    <h1>Hello client</h1>
     <hr>
    {% for post in object_list %}
<table>
                    <tr>{{ post.data }}</tr>
    <tr><th colspan="2">{{ post.usd }}</th></tr>
    <tr><td>Курс покупки</td>    <td>Курс продажи</td></tr>
    <tr><td>{{ post.usd_buy }}</td>    <td>{{ post.usd_sale }}</td></tr>
    <tr><th colspan="2">{{ post.eur }}</th></tr>
    <tr><td>Курс покупки</td>    <td>Курс продажи</td></tr>
    <tr><td>{{ post.eur_buy }}</td>    <td>{{ post.eur_sale }}</td></tr>
    <tr><th colspan="2">{{ post.rub }}</th></tr>
    <tr><td>Курс покупки</td>    <td>Курс продажи</td></tr>
    <tr><td>{{ post.rub_buy }}</td>    <td>{{ post.rub_sale }}</td></tr>
  </table>
    {% endfor %}
</article>
</body>
</html>

diplombank/bank/templates/bank/coursesdepositsbank_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BANK</title>
</head>
<body>
    <article>
        <h1>Hello {{ user }}</h1>
    {% if user.is_authenticated %}
        <p><a href="{% url 'logout' %}">LogOut()</a></p>
        <p><a href="{% url 'bank:new' %}">Create deposit()</a></p>
        <p><a href="{% url 'bank:deposit' %}">View your deposit()</a></p>
    {% else %}
        <p><a href="{% url 'login' %}">Authorization()</a></p>
        <p><a href="{% url 'signup' %}">Registration()</a></p>
    {% endif %}
     <hr>
     <hr>
    {% for obj in object_list %}
        <table>
                    <tr>{{ obj.date }}</tr>
        <tr><th colspan="2">{{ obj.usd }}</th></tr>
        <tr><td>Purchase rate</td>    <td>Selling rate</td>    <td>Deposit rate</td></tr>
        <tr><td>{{ obj.usd_buy }}</td>    <td>{{ obj.usd_sale }}</td>    <td>{{ obj.rate_usd }}</td></tr>
        <tr><th colspan="2">{{ obj.eur }}</th></tr>
        <tr><td>Purchase rate</td>    <td>Selling rate</td>    <td>Deposit rate</td></tr>
        <tr><td>{{ obj.eur_buy }}</td>    <td>{{ obj.eur_sale }}</td>    <td>{{ obj.rate_eur }}</td></tr>
        <tr><th colspan="2">{{ obj.rub }}</th></tr>
        <tr><td>Purchase rate</td>    <td>Selling rate</td>    <td>Deposit rate</td></tr>
        <tr><td>{{ obj.rub_buy }}</td>    <td>{{ obj.rub_sale }}</td>    <td>{{ obj.rate_rub }}</td></tr>
        <tr><th colspan="2">BYN</th></tr>
        <tr><td>Deposit rate</td>    <td>{{ obj.rate_byn }}</td></tr>
        </table>
    {% endfor %}
    <hr>
    <hr>
    </article>
</body>
</html>

diplombank/bank/templates/bank/profitdepositsclient_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MARGIN</title>
</head>
<body>
    <p>Me:{{ user }}</p>
    <p><a href="{% url 'bank:all' %}">Home page()</a></p>
    <p><a href="{% url 'bank:single' %}">Sum deposit()</a></p>
    <p><a href="{% url 'bank:new' %}">Create new deposit()</a></p>
    <hr>
    <hr>
    {% for obj in object_list %}
    <table>
                        <tr>{{ obj.date }}</tr>
        <tr><th colspan="2">Deposit income USD</th></tr>
        <tr><td>{{ obj.profit_usd }} usd</td></tr>
        <tr><th colspan="2">Deposit income EUR</th></tr>
        <tr><td>{{ obj.profit_eur }} eur</td></tr>
        <tr><th colspan="2">Deposit income RUB</th></tr>
        <tr><td>{{ obj.profit_rub }} rub</td></tr>
        <tr><th colspan="2">Deposit income BYN</th></tr>
        <tr><td>{{ obj.profit_byn }} byn</td></tr>
    </table>
    {% endfor %}
    <hr>
    <hr>
</body>
</html>